# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
latex: false
fortran: false

matrix:
  include: 
    - os: osx
      brew_packages: imagemagick libsodium

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
