version: 2
jobs:
  build:
    docker:
      - image: rocker/verse:latest
    steps:
      - checkout
      - run: 
          name: Install libsodium
          command: |
            sudo apt-get update
            sudo apt-get install libsodium-dev
      - run:
          name: Install package dependencies
          command: R -e 'remotes::install_deps(dependencies = TRUE)'
      - run:
          name: Session information and installed package versions
          command: |
            R -e 'sessionInfo()'
            R -e 'installed.packages()[, c("Package", "Version")]'
            R -e 'rmarkdown::pandoc_version()'
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: R CMD check --as-cran --no-manual *tar.gz
      - run:
          name: Test package
          when: on_success
          command: R -e 'covr::codecov()'
      - store_artifacts:
          path: chemspiderapi.Rcheck/
      - save_cache:
          key: r-pkg-cache--
          paths:
            - "~/R/Library"
workflows:
  version: 2
  workflow: 
    jobs:
    - build
